version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmaster
    ports:
      - "3306:3306"
